// Auto-generated
let project = new Project('armory280test');

project.addSources('Sources');
project.addLibrary("../../../Armory28/Armory_05_win64_b28/Armory/armsdk/armory");
project.addLibrary("../../../Armory28/Armory_05_win64_b28/Armory/armsdk/iron");
project.addLibrary("logic_pack");
project.addLibrary("../../../Armory28/Armory_05_win64_b28/Armory/armsdk/lib/haxebullet");
project.addAssets("../../Armory28/Armory_05_win64_b28/Armory/armsdk/lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('arm.node.SimpleFirstPerson');
project.addParameter("--macro keep('arm.node.SimpleFirstPerson')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addShaders("build_SimpleFirstPerson_B28/compiled/Shaders/*.glsl");
project.addAssets("build_SimpleFirstPerson_B28/compiled/Assets/**", { notinlist: true });
project.addAssets("build_SimpleFirstPerson_B28/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("../../Armory28/Armory_05_win64_b28/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("../../Armory28/Armory_05_win64_b28/Armory/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("../../Armory28/Armory_05_win64_b28/Armory/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('arm_voxelgi');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_depthprepass');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=4096');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=TAA');
project.addDefine('arm_veloc');
project.addDefine('arm_taa');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_gi=Voxel AO');
project.addDefine('rp_voxelgi_resolution=128');
project.addDefine('rp_voxelgi_resolution_z=1.0');
project.addDefine('rp_ssgi=RTGI');
project.addDefine('rp_bloom');
project.addDefine('rp_ssr');
project.addDefine('rp_ssr_half');
project.addDefine('rp_gbuffer2');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_skin');
project.addDefine('arm_particles_gpu');
project.addDefine('arm_particles');
project.addDefine('arm_fast');


resolve(project);
